### ISSUE TITLE
DownStylerConfiguration Link Color Not Working

### ISSUE THREAD

**Issue by RedPlumber** [iwasrobbed/Down#232] opened 2020-10-20 16:25 UTC
Please help prevent duplicate issues before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Report

## What did you do?

I have used your iOS example code to build a custom style but unfortunately the link color is not changing. 

I replaced the content of **renderDownInWebView** with this 

> let downView = DownTextView(frame: view.bounds)
let down = Down(markdownString: readMeContents)
        let styler = DownStyler(configuration: .testConfiguration)
        downView.attributedText = try! down.toAttributedString(styler: styler)
 
and I am using the DownStylerConfiguration **testConfiguration** from your test suite.

## What did you expect to happen?

In the configuration link color is set as 

> colors.link = .red  

so it should show red links

## What happened instead?

it does not show as red but as default blue

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-20 at 18 23 49](https://user-images.githubusercontent.com/1003786/96615349-72644100-1301-11eb-9983-70675d34dd2f.png)

Thanks

**Comment by johnxnguyen** [comment] 2020-10-21 07:03
Hi @RedPlumber , thanks for the report. I can confirm the issue and know the cause. I'll push a fix when I have some time.

**Comment by iwasrobbed-ks** [comment] 2020-10-21 14:35
Closed via #233 ; will release a new version soon

**Closed by iwasrobbed-ks** 2020-10-21 14:35 UTC
