### ISSUE TITLE
Adding a snapshot test framework

### ISSUE THREAD

**Issue by johnxnguyen** [iwasrobbed/Down#164] opened 2019-07-24 07:44 UTC
Please help prevent duplicate requests before submitting a new one:

* [x] I've searched other open/closed issues for duplicates before opening up this new issue.

# Feature Request

## Is your feature request related to a problem? Please describe.

The problem I'm having whilst implementing the default styler is how to write clean and concise tests for various formatting scenarios (in particular nested lists). Using standard asserts against the attributed string is cumbersome, verbose, error prone and hard to read. 

## Describe the solution you'd like

Testing attributed strings is inherently visual and I would argue that snapshot testing is particularly suitable in this case. It would remove the need to inspect attributes which would lead to much cleaner tests. It would also allow us to test formatting of the same markdown string across various screen sizes.

Additionally, we could also use non visual snapshot tests to cover the `AttributedStringVisitor`s output, instead of asserting a long markdown string that contains unicode code points. 

I would propose to use [swift snapshot testing](https://github.com/pointfreeco/swift-snapshot-testing) but am of course open to other frameworks.

I think we should keep dependencies to an absolute minimum, but this dependency would only be added to the test target and I believe it would be of great benefit.

## Describe alternatives you've considered

If adding a framework dependency is a no go, then the only alternative we have is to use standard asserts to check the values of attributes (over particular ranges) of an attributed string.

**Comment by iwasrobbed** [comment] 2019-07-25 15:00
Closing as a dupe of #165

**Closed by iwasrobbed** 2019-07-25 15:00 UTC
